import { GlobaProvider, Header } from '@/components/common';
import { cn } from '@/lib';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}): JSX.Element {
	return (
		<html lang="pt-BR">
			<body
				className={cn(
					inter.className,
					'h-fit w-full flex-col items-center justify-normal gap-2 p-4',
				)}
			>
				<GlobaProvider>
					<Header />

					{children}
				</GlobaProvider>
			</body>
		</html>
	);
}
