import { GlobaProvider } from '@/components';
import { cn } from '@/lib';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="pt-BR">
      <body className={cn(inter.className, 'h-screen w-full')}>
        <GlobaProvider>{children}</GlobaProvider>
      </body>
    </html>
  );
}
